### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by wahmedswl** [intervention-engine/ie-ccda-endpoint#9]
Hi, i have tried to run docker image ```docker run intervention-engine/ie-ccda-endpoint``` but when i browse http://localhost:3000 nothing happens and i got ```This site can’t be reached```

Any help would be appreciated in running in docker.

Thanks

**Comment by ssayer** [comment]
We only support one URL that is used for uploading CCDA. It is located at /ccda and you can see the configuration here https://github.com/intervention-engine/ie-ccda-endpoint/blob/master/config/routes.rb

Note that we don't fully convert all elements of CCDA, this is specially built to work with Intervention Engine, and we only export things we use the application
